### ISSUE TITLE
TypeError in /search

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2015] opened 2021-10-02 09:35 UTC
## Error in v3 (client side)

**TypeError** in **/search**
Failed to fetch

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/615827edc303e20008e6f5f3?event_id=615827ed0083100fcb270000&i=gh&m=ci)

## Stacktrace

    app/javascript/utils/fetch-json.ts:12 - fetchJSON
    app/javascript/utils/send-request.ts:23 - sendRequest
    app/javascript/hooks/request-query.ts:36 - 

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/615827edc303e20008e6f5f3?event_id=615827ed0083100fcb270000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment] 2021-10-03 14:05
Duplicate of #2025

**Closed as completed** 2021-10-06 13:43 UTC
