### ISSUE TITLE
Clicking "See what's changed" does not work

### ISSUE THREAD

**Issue by joshgoebel** [exercism/website#1093] opened 2021-06-07 20:57 UTC
The notice disappears, but nothing is updated and refreshing the page the notice it reappears.

<img width="672" alt="Screen Shot 2021-06-07 at 4 56 19 PM" src="https://user-images.githubusercontent.com/6473/121086582-57234480-c7b1-11eb-86ce-80f6e12e0597.png">

JavaScript error?

On: Mac Mohave / Safari 14.1

**Comment by iHiD** [comment] 2021-06-07 21:11
Thanks. It's because when there's no "important files" that have changed between updates there's nothing to show and so the modal breaks. I need to work out a solution, but its quite a tricky one. Closing as a duplicate of https://github.com/exercism/v3-beta/issues/44

**Closed as completed by iHiD** 2021-06-07 21:11 UTC
