### ISSUE TITLE
TypeError in /tracks/python/concepts

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2020] opened 2021-10-03 00:08 UTC
## Error in v3 (client side)

**TypeError** in **/tracks/python/concepts**
Failed to fetch

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6158f465b2a0830007583cfe?event_id=6158f465008317bc7b8c0000&i=gh&m=ci)

## Stacktrace

    app/javascript/utils/fetch-json.ts:12 - fetchJSON
    app/javascript/utils/send-request.ts:23 - sendRequest
    app/javascript/hooks/request-query.ts:36 - 

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6158f465b2a0830007583cfe?event_id=6158f465008317bc7b8c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment] 2021-10-03 14:04
Duplicate of #2025

**Closed as completed** 2021-10-06 13:42 UTC
