### ISSUE TITLE
How should we structure system tests?

### ISSUE THREAD

**Issue by iHiD** [exercism/website#54] opened 2020-09-02 22:31 UTC
With reference to this discussion: https://github.com/exercism/v3-website/pull/53#r482050626_

I think we want two different things here. And I think probably we want a test for each.

- I want something that uses the app as a user does but where we verify that the correct things are happening under the hood. Without this test, there's nothing in our test-suite that actually checks that things work as expected. These are effectively integration tests, but I want them to use the Chrome for the testing, not me manually specifying the routes to traverse (which I find prone to bugs).
- You want something that tests the flow of the app specifically from how a user is perceiving it. That's really valuable too.

My issue is when we combine the two, making view-level changes, break the "functional" test that I want, which I find really frustrating. And that's even more acute at this early stage, as the actual views are effectively nonsense, but I still want to have proper functional tests that don't then break when we implement the views.

---

So maybe the key here is to have the tests in two different subdirectories where it's clear what the purpose of each is?

**Comment by kntsoriano** [comment] 2020-09-02 23:23
I think the system tests should serve as "functional" tests, and separating them into directories would just duplicate tests. If we wanted to assert that the tracks was successfully joined by the user, the page where the user is redirected to should assert that the track is joined, and should display the correct message. If there are edge cases during track creation, that could then fit into the service class test, or another system test if ever we're displaying error messages.

I'm okay with how we're doing it right now since the views aren't finalized yet, but once we somewhat a rough idea of what it is, we should move into asserting what the user sees. I think we should write something just to clear this up while we're in a transitional phase and still figuring things out.

**Comment by iHiD** [comment] 2020-09-02 23:23
@kntsoriano Let's continue the discussion here 🙂

**Comment by iHiD** [comment] 2020-09-02 23:25
> I'm okay with how we're doing it right now since the views aren't finalized yet, but once we somewhat a rough idea of what it is, we should move into asserting what the user sees.

Can I ask a question the other way to maybe help make this clearer. At what point do you decide a system test is worth writing? And then how do you choose which element on the page to check? Is the element on the page that you check actually the thing you care about, or just a flag you're using to know you're on the right page?

**Comment by iHiD** [comment] 2020-09-02 23:27
> Without this test, there’s nothing in our test-suite that actually checks that things work as expected.

Also - I'd like to understand where you feel this goes, if not here.

**Comment by kntsoriano** [comment] 2020-09-03 00:06
I usually write the system test as my first test in order to drive my code. I do it this way because at that point this is the only thing that I am sure of. How I structure the models and controllers would slowly unfold as I make the test pass.

The assertions that I have on the system test is just an approximate that gets me to where I want to be. It maybe is a message that says that you've joined the ruby track. I also make sure that I write a small assertion that isn't too specific as this could be harder to change. Maybe we could use I18n as we're pretty sure we're using it in V3 and on this page, and we're not hard coding any text in the system test. Skinning the pages in the future might be complicated when there's a test already, and I understand that completely. I want to get to a good middle ground that works :)

> Also - I'd like to understand where you feel this goes, if not here.

I feel that this test shouldn't be anywhere. If we have something that asserts the person is on the correct page after joining the track, then I'm completely fine with that. The test will fail anyway if the controller action it redirects to finds a track membership that isn't created. If there are any side effects, we would most likely be using a service class to do those side effects. We should then test the side effects on the service class test.

**Comment by SleeplessByte** [comment] 2020-09-03 00:32
Without trying to comment on everything, I do agree here that the system test should not access the database, and I think that should be a rule. Create data under your control if you need, but done assert the db.

You need two tests:

A controller test that tests that you've joined the track.

A system test that doesn't have access to the database. I would probably, myself, write it as "join" and then "check if url or button is correct that wouldn't be if you had not joined the track".

In reality, if the user hasn't actually joined the track but can do everything they would want to do... Does it really matter? If it does, then the test isn't good enough. If it doesn't, great.

**Comment by iHiD** [comment] 2020-09-03 13:01
So, I think the things both of you are talking about makes total sense in the landscape of sort of "classical" rails system tests. And for controller tests the same. I'm not against or disputing the value of those tests. That said, I do think that asserting text exists on a page for the sake of checking something has happened correctly isn't a great pattern. I think if we assert something, we should be asserting the existence of that thing because we care about that thing (e.g. "In reality, if the user hasn't actually joined the track but can do everything they would want to do... Does it really matter"), rather than using some strings to signify that we're on the right page etc. So I would want any assertions to be meaningful, not side effects. For example, if we're checking we're on the right page, then assert the body's class (which containers controller/action), rather than the existence of the string "Welcome to Ruby", which could be on lots of pages, and is a very weak guarantee of success.

However, what I personally care more about is an integration test that checks that when a person clicks around on the website the code all actually fits together and works as expected. The set of [controller tests, model tests, and system tests that don't access the database] test all the composite components, but they don't catch things like a page having incorrect routes, or changes to names that are mocked, or a form field that doesn't translate properly, or the fact then when you submit via the editor the file doesn't get uploaded to s3 properly, or lots of other bits "integration" bits. Rails has integration tests which are for this purpose. To quote the Rails docs:

> Integration tests are used to test how various parts of your application interact. They are generally used to test important workflows within our application.

What I want is integration tests that use Chrome rather than Rails integration helpers, as they give an even safer set of tests.

---

Fundamentally, I sleep better knowing that there are full integration tests that check things end-to-end at the different levels (s3, dynamodb, mysql, etc). That level of testing is important to me, its caught many regressions in the past for me, and it also helps to TDD. So it's something I want us to have in this app.

There are two ways we can do it:
1. Change the integration tests to use Capybara (I don't know how easy/hard that is to do - I've not looked)
2. Have a separate set of integration tests that use Capybara which can be called something else (`interactive_integration_tests` etc).

Do you have thoughts/opinions on how we structure this?

**Comment by ErikSchierboom** [comment] 2020-09-03 13:55
It's hard for me to comment on the Ruby side of things, but I've written quite some web-based integration tests at my previous employer. Several things stood out to me:

1. They are hard and time-consuming to write.
1. They can be brittle if they depend too much on the structure of the website.

But also:

1. They are very important to having confidence in the correct functioning of your application.
1. They saved my ass several times, where otherwise I would have introduced a regression test.

A rule was imposed upon us to _not_ access the database in any way and only interact/test things using what is rendered to the browser. While I understood the idea behind this, this had all sorts of less fortunate effects:

1. It was sometimes very hard to verify if something was executed correctly. This could be due to timing (something happening in the background) or the result being a side-effect of some sort that could not be identified in the browser. To fix the latter, stuff was added to the HTML output just get the integration test to pass.
1. Tests were far slower than being able to do a bit of database setup before/after tests to speed things up. I found this to be really important, because slow tests are not run as often as fast tests (and this proved to be the case).

So I'm definitely in favor of doing system tests, but I'm not opposed to also checking more things. 

I don't know if any of the above helps :)

**Comment by SleeplessByte** [comment] 2020-09-03 15:44
In my restrictions for front end system tests you can access the database to setup the test, just not to assert.

I understand what you want @iHiD and I feel that it makes sense. I think I still worry for those test to "test too much", but I think it makes sense to:

- when a user clicks a button...
- assert that they join a track

Terminology here is not on our side (e2e integration system etc.) and rails doesn't do a great job either.

---

Testing that the user now has the track in their track list on the db level makes the test brittle. You're testing implementation, and can not change how user's tracks are modelled without changing a test _when form a public API standpoint nothing changes_.

I don't think it's particularly bad to check the database here, but I don't think it's what you want.

What you really want is I think:

1. A user is not part of a track
2. When browsing tot he track it sees the join button
3. A user clicks the button
4. A user can now see the track contents

Those are all visual public API tests, and the text is under your control because you can create the track inside the test (and you should).

You also want the following test:

1. A user is part of a track
2. When browsing to the URL, a user can see the track contents.

Both tests don't break when implementation details change. They don't break if you decide to use Django or Laravel instead of Rails. They allow you to have tests as if you're the user.

When you need to query the database to check if something happened, either there is no public consequence to the something that should have happened (and thus doesn't need to be tested from a user perspective), is too complex to be tested regularly (and should be a manual test, for example checking if an email is sent -- which you can't test e2e properly, just approach it) or has a public consequence that you CAN test.

---

I think wanting to test the database here is a natural thing to want, but is brittle and gives maybe a false sense of security. It doesn't test if the user is redirected. Or can now access the page. Or can see the correct content. It just tests that the button did a request and that request has a particular side effect on a database level.

Instead, you want to test the side effect on the public level, and have a controller test that tests the database part.

**Comment by iHiD** [comment] 2020-09-03 19:53
Thank you all for your thoughts. It's really great to see us all caring about getting this stuff right.

I do still feel a little like we're talking a little at cross-purposes, so let me try to be super explicit and forgive me if I'm telling you things you already understand.

So I 100% agree with system tests that test the system from the user's perspective, and I also 100% agree that these shouldn't touch the database when asserting (and agree with Erik's caveat about setup being useful). A good example is the websockets system test, which just sleeps for a second while things happen.

To pick out a specific quote from DJ:

> When you need to query the database to check if something happened, either there is no public consequence to the something that should have happened (and thus doesn't need to be tested from a user perspective)

From this "classical" system test approach, I entirely agree with this. If we're testing things that the user doesn't see **naturally** then we're doing it wrong.

I think it's important that everyone is clear that I agree with this. If that's clear, I think we can leave that bit of the discussion aside now so as not to confuse things further 🙂 

---

But I want something separate to this **as well**. As you say, @SleeplessByte, the terminology doesn't help here, so let me try and draw it out specifically.

What I want is **not** testing what the user sees or their perception of what's happening. I want to specifically know that clicking buttons does the things that I expect to happen at a deeper, more complex level. For example, I might want to test that clicking the submit button in the editor actually causes the test-run to be scheduled in DynamoDB. I can test each component on that journey individually (e.g. the system test for the button click and the pending spinner, the controller action that does it, the command that queues it) but I have no certainty that I've not missed something in those tests unless I have something end-to-end. In fact this is a good example, as the user might well see the spinning "waiting for the tests to run" even if something in the DynamoDB write fails, as this code is very async (at all levels). Only by doing that end-to-end check of "user clicks button, deep thing happens" do I get to sleep at night knowing that whatever gets merged, it's not broken that functionality. 

If you can guarantee perfect tests with 100% coverage and can guarantee that all the dots join up perfectly, then this isn't needed, but I've not worked in a codebase where sometimes tests are brittle or don't join up properly, and where this sort of e2e test is the only thing that catches it. Especially not a codebase that is complex like Exercism's and that interacts with lots of other services and moving parts.

One very big positive side-effect of that is that it allows me to review PRs quicker, and be leaner with my optimistic merging, because I don't have to walk through all the tests mentally checking all the bits cover everything.

One downside is that there become more tests, which take longer to run, and which during bigger rewrites mean that maybe more has to change. But the components I care about doing this for are not trivial things - they're bigger, important actions that have very low churn (for example, joining a track, which might change but if it does so much will have to change that this one extra bit isn't something I'd worry about). Having those things robustly tested like this, even if it feels "dirty" to y'all is a tradeoff I'm ok with in order to sleep better at night 🙂 

I'm quite clear in my mind that I want these in this codebase, because I'm happy with the tradeoffs. If that means we have to have some extra semi-duplicated tests, I don't mind that. This isn't some new idea for me - it's been a fundamental piece of every codebase I've written for a long time. But I am really happy to discuss how best to name and structure these so that their purpose is clear and we all understand why and when they should be used.

---


> When you need to query the database to check if something happened, either there is no public consequence to the something that should have happened (and thus doesn't need to be tested from a user perspective), is too complex to be tested regularly (and should be a manual test, for example checking if an email is sent -- which you can't test e2e properly, just approach it) or has a public consequence that you CAN test.

@SleeplessByte Just to address the final bit you wrote. I think there's a fourth option here, which is where there are things that are e2e and potentially complex and that can be tested regularly. These are the things I care about here.

**Comment by SleeplessByte** [comment] 2020-09-03 20:10
We must not forget that manual tests exist.

And yes, I think it's fine to do a combination test, if the reasoning is "it's too much effort to test the thing I want to test in sufficient isolation, so I test the whole thing in a flow test somewhere else and I just want a quick and dirty and potentially brittle sanity and regression test here".

I would recommend commenting it, and perhaps changing the minutest assert message to indicate it's a smoking gun but might not be shots fired.

**Comment by iHiD** [comment] 2020-09-03 22:10
I think maybe something to add clarity is that the test that initiated this discussion is an example of something that I agree **should** be tested with checking for the content of the page (although probably checking some body class, rather than text is present, as that is less brittle). And that I would be happy for that to change once that is done. However, I don't want that to lead to a general principle that we should **never** test deeper functionality using Chrome tests because I think there **is** often value in that.

DJ above wrote that manual tests have value. What I guess I'm saying here is that, where possible, automating the tests you would do manually through Chrome is a valuable thing to have if possible 🙂

**Comment by kntsoriano** [comment] 2020-09-28 10:26
Are we okay with this? Can we close this now? :)

**Comment by iHiD** [comment] 2020-09-28 19:11
Yep. Thanks everyone 🙂

**Closed as completed** 2020-09-28 19:11 UTC
