### ISSUE TITLE
Cursor in editor does not correspond to click location

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/website#742] opened 2021-04-09 07:32 UTC
I have a weird issue where the cursor does not correspond to the location that I click on with my mouse:

https://www.loom.com/share/f0d3b0c20b594885bd1219a5c5e4a109

CC @iHiD

**Comment by iHiD** [comment] 2021-04-09 15:03
@ErikSchierboom As this seems to be an issue exclusively on Windows, I've reassigned it to you to work out the cause. 🙂

**Comment by andrerfcsantos** [comment] 2021-04-09 15:19
I found this related issue:
https://github.com/microsoft/monaco-editor/issues/1626

Doing `monaco.editor.remeasureFonts()` on the console did indeed fix the issue for me.

**Comment by ErikSchierboom** [comment] 2021-04-09 16:35
@iHiD Cheeky!

**Comment by ErikSchierboom** [comment] 2021-04-09 17:15
@andrerfcsantos Brilliant! That does indeed fix it. I've submitted #750 to fix it.

**Closed as completed** 2021-04-12 10:47 UTC
